	IFND	GRAPHICS_DISPLAY_I
GRAPHICS_DISPLAY_I	SET	1
MODE_640	equ	$8000
PLNCNTMSK	equ	$7
PLNCNTSHFT	equ	12
PF2PRI	equ	$40
COLORON	equ	$0200
DBLPF	equ	$400
HOLDNMODIFY	equ	$800
INTERLACE	equ	4
PFA_FINE_SCROLL	equ	$F
PFB_FINE_SCROLL_SHIFT	equ	4
PF_FINE_SCROLL_MASK	equ	$F
DIW_HORIZ_POS	equ	$7F
DIW_VRTCL_POS	equ	$1FF
DIW_VRTCL_POS_SHIFT	equ	7
DFTCH_MASK	equ	$FF
VPOSRLOF	equ	$8000
	ENDC

