
 IFND    DEVICES_TIMER_I
DEVICES_TIMER_I SET     1
 IFND    EXEC_IO_I
 INCLUDE "exec/io.i"
 ENDC    EXEC_IO_I
UNIT_MICROHZ    EQU     0
UNIT_VBLANK     EQU     1
TIMERNAME       MACRO
  DC.B    'timer.device',0
  DS.W    0
  ENDM
 STRUCTURE TIMEVAL,0
 ULONG   TV_SECS
 ULONG   TV_MICRO
 LABEL   TV_SIZE
 STRUCTURE TIMEREQUEST,IO_SIZE
 STRUCT  IOTV_TIME,TV_SIZE
 LABEL   IOTV_SIZE
 DEVINIT
 DEVCMD  TR_ADDREQUEST
 DEVCMD  TR_GETSYSTIME
 DEVCMD  TR_SETSYSTIME
 ENDC
