	IFND	EXEC_NODES_I
EXEC_NODES_I	SET	1
	rsreset
LN	rs.b	0
LN_SUCC	rs.l	1
LN_PRED	rs.l	1
LN_TYPE	rs.b	1
LN_PRI	rs.b	1
LN_NAME	rs.l	1
LN_SIZE	rs.w	0
	rsreset
MLN	rs.b	0
MLN_SUCC	rs.l	1
MLN_PRED	rs.l	1
MLN_SIZE	rs.w	0
NT_UNKNOWN	EQU	0
NT_TASK	EQU	1
NT_INTERRUPT	EQU	2
NT_DEVICE	EQU	3
NT_MSGPORT	EQU	4
NT_MESSAGE	EQU	5
NT_FREEMSG	EQU	6
NT_REPLYMSG	EQU	7
NT_RESOURCE	EQU	8
NT_LIBRARY	EQU	9
NT_MEMORY	EQU	10
NT_SOFTINT	EQU	11
NT_FONT	EQU	12
NT_PROCESS	EQU	13
NT_SEMAPHORE	EQU	14
NT_SIGNALSEM	EQU	15
	ENDC

