	IFND	EXEC_PORTS_I
EXEC_PORTS_I	SET	1
	IFND	EXEC_NODES_I
	INCLUDE	"exec/nodes.i"
	ENDC
	IFND	EXEC_LISTS_I
	INCLUDE	"exec/lists.i"
	ENDC
	rsreset
MP	rs.b	LN_SIZE
MP_FLAGS	rs.b	1
MP_SIGBIT	rs.b	1
MP_SIGTASK	rs.l	1
MP_MSGLIST	rs.b	LH_SIZE
MP_SIZE	rs.w	0
MP_SOFTINT	EQU	MP_SIGTASK
PF_ACTION	EQU	3
PA_SIGNAL	EQU	0
PA_SOFTINT	EQU	1
PA_IGNORE	EQU	2
	rsreset
MN	rs.b	LN_SIZE
MN_REPLYPORT	rs.l	1
MN_LENGTH	rs.w	1
MN_SIZE	rs.w	0
	ENDC

