	IFND	EXEC_RESIDENT_I
EXEC_RESIDENT_I	SET	1
	rsreset
RT	rs.b	0
RT_MATCHWORD	rs.w	1
RT_MATCHTAG	rs.l	1
RT_ENDSKIP	rs.l	1
RT_FLAGS	rs.b	1
RT_VERSION	rs.b	1
RT_TYPE	rs.b	1
RT_PRI	rs.b	1
RT_NAME	rs.l	1
RT_IDSTRING	rs.l	1
RT_INIT	rs.l	1
RT_SIZE	rs.w	0
RTC_MATCHWORD	EQU	$4AFC
RTB_COLDSTART	equ	0
RTF_COLDSTART	equ	1<<0
RTB_AUTOINIT	equ	7
RTF_AUTOINIT	equ	1<<7
RTM_WHEN	EQU	1
RTW_NEVER	EQU	0
RTW_COLDSTART	EQU	1
	ENDC

