	IFND	EXEC_SEMAPHORES_I
EXEC_SEMAPHORES_I	SET	1
	IFND	EXEC_NODES_I
	INCLUDE	"exec/nodes.i"
	ENDC
	IFND	EXEC_LISTS_I
	INCLUDE	"exec/lists.i"
	ENDC
	IFND	EXEC_PORTS_I
	INCLUDE	"exec/ports.i"
	ENDC
	rsreset
SM	rs.b	MP_SIZE
SM_BIDS	rs.w	1
SM_SIZE	rs.w	0
SM_LOCKMSG	EQU	MP_SIGTASK
	rsreset
SSR	rs.b	MLN_SIZE
SSR_WAITER	rs.l	1
SSR_SIZE	rs.w	0
	rsreset
SS	rs.b	LN_SIZE
SS_NESTCOUNT	rs.w	1
SS_WAITQUEUE	rs.b	MLH_SIZE
SS_MULTIPLELINK	rs.b	SSR_SIZE
SS_OWNER	rs.l	1
SS_QUEUECOUNT	rs.w	1
SS_SIZE	rs.w	0
	ENDC

