    IFND EXEC_DEVICES_I
EXEC_DEVICES_I SET 1
    IFND EXEC_LIBRARIES_I
    INCLUDE "exec/libraries.i"
    ENDC !EXEC_LIBRARIES_I
    IFND EXEC_PORTS_I
    INCLUDE "exec/ports.i"
    ENDC !EXEC_PORTS_I
 STRUCTURE  DD,LIB_SIZE
    LABEL   DD_SIZE
 STRUCTURE  UNIT,MP_SIZE
    UBYTE   UNIT_FLAGS
    UBYTE   UNIT_pad
    UWORD   UNIT_OPENCNT
    LABEL   UNIT_SIZE
    BITDEF  UNIT,ACTIVE,0
    BITDEF  UNIT,INTASK,1
    ENDC !EXEC_DEVICES_I
