    IFND EXEC_RESIDENT_I
EXEC_RESIDENT_I SET 1
 STRUCTURE RT,0
    UWORD RT_MATCHWORD
    APTR  RT_MATCHTAG
    APTR  RT_ENDSKIP
    UBYTE RT_FLAGS
    UBYTE RT_VERSION
    UBYTE RT_TYPE
    BYTE  RT_PRI
    APTR  RT_NAME
    APTR  RT_IDSTRING
    APTR  RT_INIT
    LABEL RT_SIZE
RTC_MATCHWORD   EQU     $4AFC
    BITDEF RT,COLDSTART,0
    BITDEF RT,AUTOINIT,7
RTM_WHEN        EQU     1
RTW_NEVER       EQU     0
RTW_COLDSTART   EQU     1
    ENDC !EXEC_RESIDENT_I
